apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: production-rabbitmqcluster
  namespace: rabbitmq-system-qa
  labels: 
spec:
  replicas: 1
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
  rabbitmq:
    additionalConfig: |
      log.console.level = info
      channel_max = 700
      default_user= nttuser 
      default_pass = 221746a4c515afdb9eff8f02805a14073416f4a5
      default_user_tags.administrator = true
      management.path_prefix = /rabbitmq-ui
  service:
    type: LoadBalancer